### ISSUE TITLE
The connection to the server was unsuccessful

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitrpg-mobile#116]
Many times when loading the app I get this error:

![2013-08-30 23 23 37](https://f.cloud.github.com/assets/589911/1062137/b04ff8be-1229-11e3-83a5-5b1a4d648760.png)

I found this post where it says the problem could be a timeout when loading index.html takes too long.

Using a Galaxy Nexus.

**Comment by Piusn** [comment]
I am getting error. Any solution tried the above mentioned but no success
