### ISSUE TITLE
Died instantly

### ISSUE THREAD

**Issue by disasterisk** [HabitRPG/habitrpg-mobile#168]
I downloaded the app for Android and when I opened it up and logged on it immediately told me I died even though my health was nearly full before. When I looked at it on my computer I had lost my sword and my health was completely full which I am pretty sure is what happens when you die so I am worried about ever trying to use it again.

**Comment by crookedneighbor** [comment]
Sorry this happened to you and that we never responded to your issue. 

I'm closing this because not only has the app changed significantly since it was opened, but we're actively working on native apps and this app will soon be deprecated.
