### ISSUE TITLE
Constantly Loading Screen after signing in with UUID/API Key

### ISSUE THREAD

**Issue by ADHDGirl** [HabitRPG/habitrpg-mobile#183]
I just downloaded the HabitRPG apps for both Android (Samsung Galaxy Tab 2) and iOS (iPhone 4S). I went to sign in via UUID/API Key. Ever since I hit the "sign in" key, I have a white screen that is loading, with the grey sync symbol spinning.

I can open the menu on the left, which has a red and yellow symbol and matching red and yellow bars. Habits, Dailies, and Rewards are all blank. To-Do shows "Active" and "Complete" tabs, but they are blank as well. Profile lists Level "null", with a red bar and yellow bar, both completely full. Below the bars, it says "Stats returning soon!"

Settings list my UUID and API Token, along with the option to Rest in the Inn and Logout. Help brings me to an explanation page, which brings me here.

I did try logging out, then back in (again, using the UUID/API Token). It freezes trying to sign in. When I exit and open the app again, I get back to the white screen with the sync spinning.

Any suggestions on how to fix it? I'd love to use the app on my devices!

**Comment by crookedneighbor** [comment]
I'm closing this because not only has the app changed significantly since it was opened, but we're actively working on native apps and this app will soon be deprecated.
