### ISSUE TITLE
iOS extremely laggy

### ISSUE THREAD

**Issue by nmynarcik** [HabitRPG/habitrpg-mobile#184]
Since the latest update, iOS 7 has been extremely laggy. Scrolling in the app is almost impossible.

**Comment by crookedneighbor** [comment]
I'm closing this because not only has the app changed significantly since it was opened, but we're actively working on native apps and this app will soon be deprecated.

**Comment by crookedneighbor** [comment]
For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon.
