### ISSUE TITLE
Character/pictures in customize are not visible!

### ISSUE THREAD

**Issue by Nornwen** [HabitRPG/habitrpg-mobile#206]
Pretty much what the title says. The app has been like this since I first downloaded it and has not been fixed in the recent update.

**Comment by Nornwen** [comment]
Logged in and out and everything is the same. :/

**Comment by crookedneighbor** [comment]
Hmmm... I'm not sure what to tell you. 

First, I want to triple check that you deleted and reinstalled it. You pressed and held the app on the home screen till it started wiggling, pressed the x button, confirmed the deletion, and then went to the app store to install it again?

If you've already done that, sorry for spelling it out. I'm just truly mystified as to why you're having these issues so I want to be very thorough about all the steps to take to troubleshoot it.

Just curious, you have ATT, so I assume you're in the US, right?

What I don't get is that you're getting a few images, but not all of them. Even if you're wearing all new Winter gear, you should still be able to see the avatar underneath. Here's mine wearing the Penguin Suit:
![2015-01-01 16 17 34](https://cloud.githubusercontent.com/assets/2916945/5593404/d2b273cc-91d1-11e4-8787-2cf3f43bb335.png)


@lefnire Do you know when the next iOS App Store update will be submitted? Nornwen is up to date with the same version I have on my iPhone, but I wonder if just submitting an update for the most recent changes would solve the problem.

**Comment by Nornwen** [comment]
It's okay. Plus I'm am not really too concerned about it, I just want to help out. (The app is still useable, and I mostly use the site.)

I did uninstall it and install it in the way you described.

I am in the US.

It's really strange, especially how none were showing at first, and then some were and some weren't. I wonder what changed.

**Comment by crookedneighbor** [comment]
@Nornwen a new mobile app update should be ready in the next two weeks. I'll check back in with you once it gets released to the App Store.

**Comment by crookedneighbor** [comment]
Forgot to check back in, but there is a new iOS app out.

You [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).
