### ISSUE TITLE
General sluggishness

### ISSUE THREAD

**Issue by fragmental** [HabitRPG/habitrpg-mobile#218]
I'm not sure how much is caused by my phone being old, and how much is not, but a lot of tasks take longer than I would like.  In a productivity app, waiting for something to happen just feels...unproductive.

The load times aren't huge.
6-7 seconds to load the app itself(possibly more on the first load)
about 2 seconds to load my habits, dailies or rewards, and about 4 seconds for my todos.  Chat takes about 7 seconds to load.  Occasionally, they will take longer though, and I always feel this uncertainty about whether I'm waiting for it to load, or I just didn't hit the button right.

It's not altogether terrible, but it just feels highly unproductive for a productivity app.

**Comment by blnk2010** [comment]
Why did this get closed? It still seems like an issue.
