### ISSUE TITLE
external links bug

### ISSUE THREAD

**Issue by huaruiwu** [HabitRPG/habitrpg-mobile#227]
On the profile page, Stats tab, the links all open within web-view of the app, causing the app to get stuck and not being able to go back. The user is then forced to remove the app from memory and restart it. The problem is in the profileStats mixin which is inside the habitrpg module. (maybe I should post this there?)

**Comment by negue** [comment]
Should we wait until the App Update is available?

**Comment by crookedneighbor** [comment]
If it's merged in, close it now.
