### ISSUE TITLE
equipment missing from equipment page in Android app

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-mobile#268]
Original issue report: https://github.com/HabitRPG/habitrpg/issues/3928
User ID: 0d91f7d6-588d-4d54-822f-8bf8c4b2141c (Pichu0102 in GitHub)
Device: HTC One m7, Verizon edition
Android app version: v0.0.35

Pichu0102 owns this gear: armor_mystery_201407, armor_mystery_201408, armor_special_gaymerx, armor_warrior_1, head_mystery_201407, head_mystery_201408, head_special_gaymerx, head_warrior_1, head_warrior_2, shield_warrior_1, weapon_warrior_0, weapon_warrior_1

The only item showing in the battle gear and costume screens in the app is armor_mystery_201407

The original issue report has screenshots from the app.

**Comment by tohn** [comment]
Since this is also an issue for me, could you please describe how to fix this? I'm running HabitRPG on my local system. Thanks!
It may depend on the Ultimate Gear award? I have every armor for all classes, but only some rogue and some warrior equipment (and some special ones) in my inventory. And my avatar doesn't have any but some are listed in my stats.

**Comment by crookedneighbor** [comment]
@tohn Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api)

Would you also take a screenshot of your settings page, the equipment page, and the stats page?

**Comment by crookedneighbor** [comment]
@tohn Though, if you're running the app locally, your user id won't actually be much help... Still, post it anyway just in case.

**Comment by tohn** [comment]
@crookedneighbor Ok, my ID is: 315f8f9c-791e-4935-adf9-fb7e4fd2e215. It's the same as my local ID.
Attached the screenshots. Thanks in advance! :)
![2015-01-05-174619_3520x1080_scrot](https://cloud.githubusercontent.com/assets/427159/5616282/6cf9b61e-9503-11e4-9cdf-6a3e748e2985.png)
![2015-01-05-174700_3520x1080_scrot](https://cloud.githubusercontent.com/assets/427159/5616284/6d07d30c-9503-11e4-90ec-6851a8f296bc.png)
![2015-01-05-174722_3520x1080_scrot](https://cloud.githubusercontent.com/assets/427159/5616283/6d038590-9503-11e4-96f7-77af61776ba6.png)

**Comment by crookedneighbor** [comment]
Ahh, I misunderstood what you meant by your local system. I thought you were saying you had downloaded the source code from Github and were running your own version on your local machine.

I'm still a little confused on a few counts though:

1) These screenshots look like the web app, not the mobile app. Are you having issues with the web app? Or with using the mobile app? It's possible you're using the web app in a browser on a mobile device.

2) I did a check of your user and this is the equipment owned I see:

``` JSON
        "armor_rogue_1": true,
        "armor_rogue_2": true,
        "armor_special_gaymerx": true,
        "armor_warrior_1": true,
        "armor_warrior_2": true,
        "head_rogue_1": true,
        "head_rogue_2": true,
        "head_rogue_3": true,
        "head_special_gaymerx": true,
        "head_warrior_1": true,
        "head_warrior_2": true,
        "head_warrior_3": true,
        "shield_rogue_0": true,
        "shield_rogue_1": true,
        "shield_rogue_2": true,
        "shield_warrior_1": true,
        "shield_warrior_2": true,
        "weapon_rogue_0": true,
        "weapon_rogue_1": true,
        "weapon_rogue_2": true,
        "weapon_warrior_0": true,
        "weapon_warrior_1": true,
        "weapon_warrior_2": true,
        "eyewear_special_summerRogue": true,
        "head_special_nye": true
```

It looks like you're missing the new year's hat, and some seasonal gear for the rogue. Is that correct? Can you clear your cache and refresh the page?

**Comment by tohn** [comment]
No, I'm really running the app on my own server ;)
So the screenshots are from my HabitRPG installation.

And it's the web app, I'm talking about, I just answered here, since I only found this issue. But it belongs to the web app, you're right.

This is the equipment in my local installation:

      "owned": {
        "armor_rogue_1": true,
        "armor_rogue_2": true,
        "armor_warrior_1": true,
        "armor_warrior_2": true,
        "head_rogue_1": true,
        "head_rogue_2": true,
        "head_rogue_3": true,
        "head_warrior_1": true,
        "head_warrior_2": true,
        "head_warrior_3": true,
        "shield_rogue_0": true,
        "shield_rogue_1": true,
        "shield_rogue_2": true,
        "shield_warrior_1": true,
        "shield_warrior_2": true,
        "weapon_rogue_0": true,
        "weapon_rogue_1": true,
        "weapon_rogue_2": true,
        "weapon_warrior_0": true,
        "weapon_warrior_1": true,
        "weapon_warrior_2": true,
        "weapon_rogue_3": true,
        "armor_rogue_3": true,
        "shield_rogue_3": true,
        "head_rogue_4": true,
        "shield_rogue_4": true,
        "weapon_rogue_4": true,
        "head_rogue_5": true,
        "armor_rogue_4": true,
        "weapon_rogue_5": true,
        "shield_rogue_5": true,
        "armor_special_gaymerx": true,
        "head_special_gaymerx": true,
        "armor_rogue_5": true,
        "headAccessory_special_summerRogue": true,
        "weapon_rogue_6": true,
        "shield_rogue_6": true,
        "weapon_special_fallRogue": true,
        "armor_special_fallRogue": true,
        "head_special_fallRogue": true,
        "shield_special_fallRogue": true,
        "weapon_healer_0": true,
        "weapon_healer_1": true,
        "weapon_healer_2": true,
        "weapon_healer_3": true,
        "weapon_healer_4": true,
        "weapon_healer_5": true,
        "weapon_healer_6": true,
        "weapon_special_fallHealer": true,
        "armor_healer_1": true,
        "shield_special_fallHealer": true,
        "shield_healer_1": true,
        "head_healer_1": true,
        "head_healer_2": true,
        "head_healer_3": true,
        "shield_healer_2": true,
        "shield_healer_3": true,
        "armor_healer_2": true,
        "armor_healer_3": true,
        "head_healer_4": true,
        "head_special_fallHealer": true,
        "shield_healer_4": true,
        "head_healer_5": true,
        "shield_healer_5": true,
        "armor_special_fallHealer": true,
        "armor_healer_4": true,
        "armor_healer_5": true,
        "head_warrior_4": true,
        "weapon_special_fallWarrior": true,
        "weapon_warrior_3": true,
        "head_special_fallWarrior": true,
        "shield_special_fallWarrior": true,
        "armor_special_fallWarrior": true,
        "shield_warrior_3": true,
        "head_warrior_5": true,
        "armor_warrior_3": true,
        "weapon_warrior_4": true,
        "shield_warrior_4": true,
        "weapon_warrior_5": true,
        "weapon_warrior_6": true,
        "armor_warrior_4": true,
        "shield_warrior_5": true,
        "armor_warrior_5": true,
        "weapon_wizard_0": true,
        "head_wizard_1": true,
        "head_wizard_2": true,
        "weapon_wizard_1": true,
        "armor_wizard_1": true,
        "armor_wizard_2": true,
        "head_wizard_3": true,
        "weapon_wizard_2": true,
        "head_wizard_4": true,
        "armor_wizard_3": true,
        "weapon_wizard_3": true,
        "head_wizard_5": true,
        "armor_wizard_4": true,
        "weapon_wizard_4": true,
        "armor_wizard_5": true,
        "weapon_wizard_5": true,
        "weapon_wizard_6": true,
        "head_special_2": true,
        "shield_special_winter2015Healer": true,
        "head_special_winter2015Healer": true,
        "armor_special_winter2015Healer": true,
        "weapon_special_winter2015Healer": true,
        "weapon_special_snowflake": true,
        "armor_special_snowflake": true,
        "head_special_snowflake": true,
        "shield_special_snowflake": true,
        "weapon_special_yeti": true,
        "armor_special_yeti": true,
        "head_special_yeti": true,
        "shield_special_yeti": true,
        "weapon_special_ski": true,
        "armor_special_ski": true,
        "head_special_ski": true,
        "shield_special_ski": true,
        "weapon_special_candycane": true,
        "armor_special_candycane": true,
        "head_special_candycane": true
      }

And the "ultimateGear" was true, but also changing to false (and disabling some armor) did not help.
It's also nothing with the cache, the spritesmith-files are correctly loaded ..

**Comment by crookedneighbor** [comment]
@tohn Just checking, but you've updated the habitrpg-shared repo as well as the main repo and restarted the express app, right?

**Comment by crookedneighbor** [comment]
Also, just curious, is there a particular reason you're running the app on your own server? IE, did you customize something for your needs? Or is it just so that you're the only one who has access to the database? Or what?

Would just like to know :smile: . Especially if you did some customization. Maybe it's something we could add to the main site!

**Comment by tohn** [comment]
Usually I move my old habitrpg folder away and clone the repo again. I then only change the config (SESSION_SECRET and ADMIN_EMAIL), do a `npm install` followed by `npm start`. If this runs fine, I change NODE_ENV in the config to `production`, run `grunt build:prod` and `grunt nodemon`.
So the database didn't change since ca. 6 months (I just imported the userdata.json from the normal HabitRPG web app). And the habitrpg-shared should get updated via `npm install`, right?
What do you mean with express app?

The reason why I run it on my server is that the data only belongs to me. And because I can ;)
I didn't do any special customization (except changing some stuff so it runs fine, I will report some bugs later), but I have some ideas. And if I do, you'll get a pull request :)

**Comment by Alys** [comment]
@tohn If you're keeping your local content from the HabitRPG/habitrpg and HabitRPG/habitrpg-shared repos up to date then you should be getting all the latest content including all purchasable equipment. Much of the special equipment is only buyable during specific time periods, so that might be why you can't see it in the Rewards column. You'd need to edit the time period in the code or manually add the gear keys to your user account.

Note also that in HabitRPG/habitrpg/migrations there are scripts that are sometimes run to update all user accounts. You'll want to regularly watch that directory and assess any changes to see if you need to run them on your own local user account.

This issue that we're on now is very different than the problems you are having. It's specifically related to the mobile app, and is not a problem caused by a broken local install. If you're not able to get your local installation working with the information we've given you here so far, please log a new issue in the HabitRPG/habitrpg repo, and include any error messsages you might be seeing.
