### ISSUE TITLE
Push Notifications [$60]

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-mobile#283]
We'd like to add Push Notifications to the mobile app that people can set to tell them when they have undone Dailies. It's a much-requested feature and would definitely help people remember to check in. Making this ticket to put a Bounty on it! 

Brainstorming ideas for functionality:
- Can set to notify X hours before cron? Or just at a certain time of day? 
- Notifies that you have X Dailies undone
- Possibly ability to have more than one set time for push notifications (e.g. one at 10 AM and one at 11 PM)

**Comment by josefc** [comment]
Hmm, looks interesting. I'm going to try it. Hopefully I can get somewhere with this

**Comment by crookedneighbor** [comment]
@josefc we are in the midst of building a native app for Android (the ios one is already out), so we are no longer accepting feature pr's for the phonegap app.

**Comment by josefc** [comment]
Oh ok. Just stumbled on this today. Good luck with your native Android app
