### ISSUE TITLE
Nothing saved!

### ISSUE THREAD

**Issue by adelphis** [HabitRPG/habitrpg-mobile#296]
I added a bunch of habits, dailies, and to-dos while on public transit today (with an internet connection active), and they showed up on my phone, but not on the website. Then I closed and reopened HabitRPG on my phone... and all my changes were gone.

Is this a common occurrence? Does the phone version work at all? I want to know if the program works before I adopt it as a big part of my productivity life.

(Note: iPhone4, windows computer at home. Website inputting worked at home, but phone input... all lost.)

**Comment by mkbeck** [comment]
Nearly all my to do list items are gone.  I definitely won't be re-entering them.  If the supper can retrieve them. Okay. Or else I'm moving on to a different app.

**Comment by mkbeck** [comment]
*support

**Comment by lefnire** [comment]
@mkbeck what's your [User Id](http://habitrpg.wikia.com/wiki/API_Options)?

**Comment by mkbeck** [comment]
meghankbeck

 

Meghan K. Beck

Director of Business Development, 1337 Holdings

Member, Edison Enterprises & Dirt Cheap Surplus

401 Market St

Sunbury, PA 17801

Phone: 570-286-5605

Fax: 570-286-1916

Cell: 570-412-7889

**Comment by mkbeck** [comment]
Any news on this issue.

**Comment by mkbeck** [comment]
?

**Comment by paglias** [comment]
@mkbeck our db shows that you have several tasks in your account as habits, dailies and also todos. Could you please tell us the name of one you're not seeing anymore? If you don't want to share it publicly you can send me a message at matteopagliazzi@gmail.com

**Comment by kbaskett** [comment]
I am struggling with the same bug. I set up my habitrpg account several weeks ago, and as long as I use the browser to update To-Dos all goes well. Then one evening last week I made many deletions, additions, and check-offs to my To-Dos and Dailies in the mobile app while connected to the internet. The next day my Tasks were back to how they had been before the updates I made on my mobile. The updates I had made using the mobile app, the deletions and additions, were gone, as well as (I suspect but can't be sure) the check-offs I had made in Dailies. I immediately checked the web version, which was in agreement with my mobile device that all the updates had been lost. 

I strongly suspect this is the same synch bug that is raised in issue #280, #292, #319, #314 . The behavior described in all these tickets I have observed and is consistent with this delete-before-synching bug. 

HabitRPG iPhone app v0.038
iOS 8.1(12B411)
iPhone 5 (NE490LL/A)

**Comment by paglias** [comment]
Sorry guys, we have discovered what probably caused this. We will push an update as soon as possible and after updating the app it should be ok, Let us know if it doesn't work

**Comment by kbaskett** [comment]
Thanks a million! Will keep an eye out for the update and write back if the issue persists. You guys have a great product, thanks for donating your time and effort so we can get the most from it.

**Comment by mkbeck** [comment]
thx

 

Meghan K. Beck

Director of Business Development, 1337 Holdings

Member, Edison Enterprises & Dirt Cheap Surplus

401 Market St

Sunbury, PA 17801

Phone: 570-286-5605

Fax: 570-286-1916

Cell: 570-412-7889

**Comment by RareBlackAngel** [comment]
I have been having similar issues, I keep losing habit I enter. My boyfriend also created an account and is having the same issue. We are both on mobile devices, but using wifi.

**Comment by TheChumBucket** [comment]
If you edit items through the app try this https://github.com/HabitRPG/habitrpg-mobile/issues/367. As long as you open the app online, leave it running in the background if you go offline, the progress should be saved once you get back online and sync. Try syncing often, not only to prevent progress loss but to help identify when the bug is activated.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
