### ISSUE TITLE
Christmas gear not showing in mobile app and adds no stats

### ISSUE THREAD

**Issue by SolarFlare3** [HabitRPG/habitrpg-mobile#317]
I wasn't able to see the winter gear until I went to the website. Then I bought them and put them on and my avatar is shown with nothing on in mobile app. So I tried to use the checklist on the website and even though it shows the armor it still acted like I had no stats. I have since put my old gear back on. I tried using it as a costume but it still gave me 0 stats on the website and shows as nothing on the mobile app. I also keep hearing about these penguins people were getting. I don't show a space for them in the stable.

**Comment by SolarFlare3** [comment]
I am getting 2 gold in app and 4 gold on website for same color task. I believe when I logged in site it updated that 2 to a 4. I will be using the website more often now

**Comment by crookedneighbor** [comment]
Yeah, that's too be expected for now. As long as the actual amount you are getting is updating on the web app, it should all work itself out.

**Comment by SolarFlare3** [comment]
The latest update fixed this Thanks!!! Habit RPG is great!
