### ISSUE TITLE
Checking off daily doesn't visibly change its state

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitrpg-mobile#323]
As of 0.0.45, checking off a daily doesn't change it from non-checked + colored to checked + grey. Seems to be some sort of bindonce issue, since switching pages and coming back shows the task in the correct state. @negue possibly anything in recent changes?

**Comment by negue** [comment]
```jade
ng-class='::[getClass(task.value),"task-#{k}",(task.completed || notDue(task)) ? "completed" : ""]')
```

hmm.. yep my bad :/

gonna try to refactor it, 

@lefnire  is it possible to use an jade `if' inside an element line? , because I would like to add this task.completed watch just for dailies

**Comment by lefnire** [comment]
You can do ternaries, like `class='#{whatever ? "this" : "that"}'`

**Comment by lefnire** [comment]
I'm going through a lot of the recent commits, and it looks like `::` is being added to just about everything. Notifications, `task.*`,  etc. FYI on `::`, it should only be added to *static* variables - variables which will not change while the app is open. Everything inside `task` is subject to change, except `.id`. I'm gonna go through and revert a few, pretty critical for a hotfix deploy
