### ISSUE TITLE
username+password login screen has contradictory message warning about uuid+token

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-mobile#326]
Under some circumstances, the app's login screen (which requires userNAME and password) will produce a contradictory message that implies incorrectly that the user has to enter their UUID and API Token:

![screenshot_2015-01-09-16-46-03](https://cloud.githubusercontent.com/assets/1495809/5690749/910fc740-98ec-11e4-9c7c-08b0f714a1dd.png)

This happens when I log out of the app, close the app, and then reopen it; the UUID+token message appears before I've had a chance to enter anything. It might also occur under other circumstances.

This is no big deal for an experienced user, but is confusing for others, especially when they have some knowledge of UUIDs but aren't really sure of the difference to usernames. I've tried to help users in the past who have given me contradictory information about what the app is asking for, and I think this message is why. I've also seen reports from users who've tried odd combinations of username, uuid, password, and token and have become very frustrated. 

The message seems to be warning that the uuid and token are missing from some internal location (which makes sense when the user isn't logged in) but I'm not sure if it provides any value to the user. Can it be suppressed when the user is viewing the login screen? Or just suppressed everywhere? I think it's likely to be more troublesome than helpful.

This might be related to https://github.com/HabitRPG/habitrpg-mobile/issues/306

**Comment by Alys** [comment]
Sorry, forgot to mention: This might be related to https://github.com/HabitRPG/habitrpg-mobile/issues/306

**Comment by john-pettigrew** [comment]
I believe I can take a look at this. While looking for a solution, I was having trouble figuring out what the "group" module is used for in the app. Any ideas?

**Comment by DavidGinzberg** [comment]
This may be only minorly relevant, but I've noticed that this message appears twice (two orange bars stacked with the same message in each) upon logout. Noticed this while testing another possible bug.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
