### ISSUE TITLE
habitrpg-shared/* not being copied into www on build

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitrpg-mobile#329]
As @negue pointed out, the solution is changing `bower_components/**/*`  => `bower_components/**/**/*` in gulp `copy` array. I don't know why, my initial thought was a gulp version upgrade, but all packages are pinned. I'm pushing a commit now to fix this, but I wanted to record this issue in case the commit causes problems or others have better ideas

**Comment by negue** [comment]
maybe the global gulp version is higher than the pinned local one?
