### ISSUE TITLE
Wintery Colors Options not displaying on Avatar

### ISSUE THREAD

**Issue by Dranian** [HabitRPG/habitrpg-mobile#330]
Hi there,

I noticed that my "Wintery Colors" hairstyle would not display on the mobile app—what should I do to correct this bug? :-)

Thanks!

Dranian

**Comment by crookedneighbor** [comment]
The wintery colors will be added to the app in the next update, so look out for it!

Are you using Android or iOS? I ask because the iOS app store has a longer review process for app updates.

**Comment by Dranian** [comment]
Awesome, thanks for the news! :)

Per your inquiry: I use iOS.

Cheers,

On Sun, Jan 18, 2015 at 10:22 PM, Blade Barringer <notifications@github.com>
wrote:

> The wintery colors will be added to the app in the next update, so look
> out for it!
>
> Are you using Android or iOS? I ask because the iOS app store has a longer
> review process for app updates.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HabitRPG/habitrpg-mobile/issues/330#issuecomment-70442111>
> .
>



-- 
Best regards,

Devin

**Comment by crookedneighbor** [comment]
Yep, I'm on iOS too. The update just hasn't been accepted into the App Store yet.
