### ISSUE TITLE
iOS sync problems

### ISSUE THREAD

**Issue by wswld** [HabitRPG/habitrpg-mobile#340]
I've already reported a major loss of data due to this issue on the main repo. I will add it here as the issue persists of now, after the latest update on iOS 8. 

Here is how to reproduce the bug:
1. Go to any to-do or habit and press edit. 
2. Edit something (checklist, name, date - anything).
3. Press save and go to menu.
4. Try to sync - preloader not showing, sync doesn't occur.
5. You may edit something else or even add data.
6. On restart all the data you edited/added after the first edit is lost.

Sync seems to break after editing issues and break hopelessly as any other change before the app is restarted gets lost after the restart.

**Comment by paglias** [comment]
cc @negue
Il 10/feb/2015 09:13 "Vsevolod Glumov" <notifications@github.com> ha
scritto:

**Comment by negue** [comment]
@paglias  Just tested on android, works.

Seems on iOS there are many sync problems lately, but I can't check it for iOS

Which was the last checkin, the iOS Update was built? @lefnire

**Comment by lefnire** [comment]
@negue HEAD https://github.com/HabitRPG/habitrpg-mobile/commit/ec75dfa40ddf0bcef2a9f6022152d7d0aeddd7c5

**Comment by negue** [comment]
huh... and of the shared repo ?

**Comment by paglias** [comment]
it's the commit at the time of the push I think

2015-02-10 17:47 GMT+01:00, negue <notifications@github.com>:
> huh... and of the shared repo ?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg-mobile/issues/340#issuecomment-73734940


-- 
Matteo Pagliazzi - paglias.net

**Comment by ModernHedonist** [comment]
Anything going on with this? My checklists aren't saving on IOS. Major bummer - I can't remember the items I lost.

**Comment by westenra** [comment]
I get exactly the same problem myself and it's frustrating me. The app barely syncs, and the To-Do List does not sync any of the checklists I add or tick off from my iPhone.

**Comment by TheChumBucket** [comment]
https://github.com/HabitRPG/habitrpg-mobile/issues/367
I found a work-around to this bug. Hopefully this helps solve your infestations =)

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
