### ISSUE TITLE
Android: Buying gems crashed app

### ISSUE THREAD

**Issue by jonnysooter** [HabitRPG/habitrpg-mobile#345]
Hi, 

Today I've attempted to buy gems on the Android app. The screen loads up Google wallet and the purchase went through. I got a confirmation from my bank that the card had been charged and the Google payment screen said "Payment Successful". However, a few seconds after the app crashed. Now every time I open HabitRPG it immediately crashes.

I've logged into my account through a browser and haven't had any issues, except there are no gems.

**Comment by jonnysooter** [comment]
I'm using Lollipop Android 4.4.4 on a One Plus One with Cyanogenmod 11.0

**Comment by crookedneighbor** [comment]
@jonnysooter As a first step, could you try uninstalling and reinstalling the app?

Second, could you forward the receipt you got for your purchase to admin@habitrpg.com? Please include your UUID. It can be found in [settings > api](https://habitrpg.com/#/options/settings/api) (be sure to copy only the user ID, not the API Token).

**Comment by lefnire** [comment]
@negue any thoughts on this?

**Comment by negue** [comment]
I can reproduce this ... man these bugs ....

Hope I can find this bug too

**Comment by jonnysooter** [comment]
@crookedneighbor I would send my UUID, however, I cannot acces the HabitRPG website through a browser anymore - this was my last option. I'm using the latest Chrome and checked the console for any front-end errors but got nothing.

![screen shot 2015-02-23 at 3 22 12 pm](https://cloud.githubusercontent.com/assets/1653474/6339978/c885b82e-bb6f-11e4-8405-fa3e466ec826.png)

**Comment by crookedneighbor** [comment]
@jonnysooter Thank you for your patience with this. We got a recent influx of traffic and it broke
our site. We're working on it right now. If you'd like to get automatic email updates, you can go to [this issue](https://github.com/HabitRPG/habitrpg/issues/4737) and click the subscribe button.

**Comment by crookedneighbor** [comment]
@jonnysooter the site is now back online. Thanks for your patience. 

We're you able to send a receipt to admin@habitrpg.com?

**Comment by jonnysooter** [comment]
@crookedneighbor I did send an email yesterday. I'll send another one now, with my UUID, Google Wallet receipt,  and link to this report.

**Comment by jonnysooter** [comment]
Thanks for all the hard work you guys do round the clock to get this back up for all of us!

**Comment by crookedneighbor** [comment]
@jonnysooter Awesome. It may take a little while for @lemoness to get back to you, given the craziness yesterday, but we'll get you sorted out.

**Comment by jonnysooter** [comment]
@crookedneighbor I understand, and it's not a problem. However, although the main site was fixed, the Android bug I report is still going on. There might have been a confounding variable (the site was down) but now that's it's back up, the app is still not working. I'm looking for new information about the bug now that the site is functional.

**Comment by crookedneighbor** [comment]
@jonnysooter Looking back over the issue, I don't see a comment where you confirmed whether or not you tried deleting and reinstalling the app. Did you try that? Obviously that wouldn't fix the buy gems problem, but it might get you back into the app.

I'm not super familiar with the Android environment, but if there is a way to clear app data when deleting it, you should.

**Comment by jonnysooter** [comment]
https://github.com/HabitRPG/habitrpg/issues/4741
Possibly related. I've tried clearing my cache, clearing all my data, and reinstalling it, but no luck either. I managed to pull an error right before the app crashes. It says that a token and UserID is required. Not much else.

**Comment by negue** [comment]
I think I fixed it (locally), currently doing some more tests and then I'll upload it to the store... sorry this took so long

**Comment by JigmeDatse** [comment]
Looks like I also got caught by this issue.  I'm not sure if it was related at all to the 503 Error issue that I was seeing last night or not.  Will continue looking to see if any solution has been posted elsewhere, but it sounds like it might be waiting for the next update from the Play Store?

**Comment by negue** [comment]
The Update 0.51 is deployed to the playstore (may take a bit longer to get the app to all stores , so wait for 0.51 :) ). With that Update it should work again.

If you already cleared the cache you need to login again and then go to the Purchase Gems Page, once opened it'll apply all bought gems. If there is still an error please write me, but I'm pretty sure that I fixed it

**Comment by JigmeDatse** [comment]
The update was available, and once launched, it seems it is working.  Going to "Purchase Gems" displayed a little "syncing" animation, and returning to my profile, the gems are there.
The Web App also displays the gems correctly.

**Comment by jonnysooter** [comment]
This has been resolved. Thanks again for all the hard work and being so incredibly responsive!

**Comment by lefnire** [comment]
Just to reiterate the solution (sending some users this way), you'll need to update the app to v0.0.51. If your app hasn't automatically updated to 0.0.51, then you can search HabitRPG in the Play Store and there should be a manual "Update" button (where you'd normally click "Install"). Once you've updated, log in and navigate to the Purchase Gems page and wait a moment for it to try once more to handle the gems transaction. If you're still missing gems, email admin@habitrpg.com with your [User ID](http://habitrpg.wikia.com/wiki/API_Options); if the app is still crashing / experiencing issues, comment here.
