### ISSUE TITLE
App has not updated for 3 days

### ISSUE THREAD

**Issue by GabeAngel** [HabitRPG/habitrpg-mobile#348]
My device is connected to then internet via wifi and all apps that need net connection are working fine but habitRPG has not updated for 3 days. I am not able to say that I have done my dailies because they are still ticked from 4 days ago so I am probably loosing health. Any idea what's going on or how to fix it?

**Comment by crookedneighbor** [comment]
If your dailies have not reset, it's possible that you're in the Inn. When an influx of new users from imgur crashed the site, and people were unable to log in for hours, we put everyone in the inn. You can check out of the inn via the mobile app by going to the settings page.

If that's not the issue, can you post your user id here? It can be found in [settings > api on the website](https://habitrpg.com/#/options/settings/api) (be sure to copy only the user ID, not the API Token) or under settings on the mobile app (again, the UUID, not the api token).

**Comment by GabeAngel** [comment]
Thank you, I just thought to check that and I was in the inn, however my dailies have still not reset since i corrected that. Will they not rest until tomorrow now?

**Comment by crookedneighbor** [comment]
@GabeAngel Correct, all the inn does is cause the code that would reset and count up damage for dailies does not get run. It should run at the designated time (midnight by default) now that you're out of the inn.

**Comment by GabeAngel** [comment]
Ok, thank you for your help.
