### ISSUE TITLE
Lost gems

### ISSUE THREAD

**Issue by RadioactiveRatt** [HabitRPG/habitrpg-mobile#350]
I use habitrpg on my mobile device. Yesterday  I purchased $5worth of gems. Right after the transaction completed, it gave me a popup saying habitrph has stoped running. I thought that was just from the transaction so I tried to reopen the program and I got the same popup. I tried again and again but I still couldn't open it. Ithen uninstalled and reinstalled it and I was able to open the progrem but I did not receive my 20gems from my purchase. If I could possibly get my 20gems that would be awesome. Username and email is the same as the onea I used for the forums here.

Sorry for any spelling errors, I'm using my phone

**Comment by lefnire** [comment]
Hey there, terribly sorry for the inconvenience. Give the following a gander: https://github.com/HabitRPG/habitrpg-mobile/issues/345#issuecomment-76237399
