### ISSUE TITLE
Dailies not refreshing 

### ISSUE THREAD

**Issue by CabinKitty** [HabitRPG/habitrpg-mobile#351]
This is happening on desktop and in Apple apps, unsure of Android.
Dailies, once completed, don't refresh overnight and therefore remain completed. Streaks are counted, regardless of having completed the task, because the tasks are seen as complete.

That's all I've got.

**Comment by lefnire** [comment]
Hey there, follow details and solution at https://github.com/HabitRPG/habitrpg/issues/4742
