### ISSUE TITLE
Push HabitRPG to F-Droid 

### ISSUE THREAD

**Issue by Alphanumerix** [HabitRPG/habitrpg-mobile#355]
> F-Droid is an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform. The client makes it easy to browse, install, and keep track of updates on your device.

I believe that presents of this great client in this FOSS-centered app "store" is really important. Whole HabitRPG system is open-source, so F-Droid is really good place to found some active users. Maybe even power-users.

**Comment by Shadow53** [comment]
I found [this issue] (https://github.com/HabitRPG/habitrpg-mobile/issues/385) earlier as a place for news on the new Habitica app to replace the existing HabitRPG app. Seems relevant so I'll leave the link here.
