### ISSUE TITLE
Several Feature Ideas 1

### ISSUE THREAD

**Issue by Rbrinkley** [HabitRPG/habitrpg-mobile#358]
Hello! I haven't posted on here in a while and I have had a lot of ideas and suggestions that I've wanted to share but never had the time do so or felt like doing so might overwhelm people. So in that case I'm gonna try and separate the ideas into several different posts. (If anyone would rather me post as much as I can into the next post please feel free to tell me). Anyway here goes!

My Ideas/Suggestions:

___________
1) Add the ability to add difficulty to a task before submitting it.
(I believe that this can make organinzing and implementing tasks from mobile phones a lot easier to do, as the whole editing process is rather clunky and kinda dis- invites editing. I think possibly adding a small box with three buttons (i.e. easy, medium, hard) would be added and tapping the difficulty would set the choice in place. The choice could be changed and once the person is finished then the task can be submitted. 

___________

2) Add some information about beta.habitrpg.com so more mobile users can be able to know about the beta optional choice.
(I think that this can get more people to know about beta.habitrpg and be able to test out some of the beta features. A lot of mobile users would probably be willing to try out something new. This is just a minor suggestion but I think that HabitRPG could benefit from more beta-testers.

____________
3) Implement a confirmation button when making purchases or selling items (Maybe not selling, probably focus more on the buying aspect) while in the market. 
(This is something that could be used to help prevent accidentally purchasing items that one did not mean to do. I am not sure if there is already one for the market since I don't have enough gems and I would rather not accidentally spend my gems trying to see if there is one. Sorry about that. So if there already is a confirmation button then no worries.

____________

4). Ability to see whether or not a message in the tavern has been seen from the website or from mobile. 
(I like this idea a lot and I think that the main website so do this too. I will likely be posting this idea onto the main repository so I can get some feedback on how the website views it. I think it could help see who is on what platform and be able to see what limitations one might be having by using said platform. (Although the website doesn't have much limitations compared to the mobile but I think you get the point))

___________
5) Ability to see contributor tiers and color titles in the tavern chat.
(I think this can be able to help set out who is what while in the tavern. One might see a post from Lemoness or Alys, but it will look like a normal person at first. I know its kinda a minor issue but it would also spice (there's probably a less weird word to describe it but I can't think of one right now) up the chat by adding some color. Just more of aesthetics, but it would look nice)

___________

Hope this helps to spur some discussions. Please feel free to tell me what you think. Happy Coding!

UUID: 6f14571c-f2e9-4446-8e4e-591a7a3a42eb
HabitRPG Username: Rbrinkley
uuid: 6f14571c-f2e9-4446-8e4e-591a7a3a42ebHabitRPG Username: Rbrinkley

**Comment by Alys** [comment]
GitHub is intended for bug reports. Feature requests should go on Trello. It's best to stick to this approach because we get a lot of bug reports and they need usually need to be fixed quickly if they can be. If GitHub is used for feature requests as well, it makes the bug reports harder to find. Also, we get a lot of similar feature requests, or related requests for the similar features, and if they are all placed into Trello, they can all be analysed together and a consensus can be reached for the best way to implement the features. Could you please post these to Trello and then close this issue?

**Comment by Rbrinkley** [comment]
Sorry about that. I had seen other people post suggestions on github but I should have checked to make sure. I apologize for the mix up and I will try to avoid doing it in the future. I'd be happy to post these in trello. Happy coding!

**Comment by Alys** [comment]
No worries. Easy mistake to make, especially since you're correct that others have done so. We're cracking down on them too. :)

**Comment by Rbrinkley** [comment]
Done! https://trello.com/c/LlJccgmY/293-chat-tavern-talk-enhancements-party-talk-enhancements ,  https://trello.com/c/exaF7GiC/135-to-dos-v2-frozen-to-do-attack-to-do   ,   https://trello.com/c/FvM7nBfa/282-edit-mode-enhancements .  I wasn't entirely sure where to post it. I was able to post all of the suggestions except for the third one. I have to head to bed soon and I haven't been able to find the correct card. Do you might happen to know where I can post it? I have to head to bed right after this so I wont be able to respond until later on. Sorry about that.
