### ISSUE TITLE
Top entries of Habits list duplicate and replace bottom entries in list. [Android 4.3]

### ISSUE THREAD

**Issue by Sduibek** [HabitRPG/habitrpg-mobile#365]
Sometimes when I open up the app, the list of Habits is all out of order.
If I switch to something else (say, Dailies) and then back, the list has corrected itself.

**HabitRPG**          0.0.50
**Device**                    SGH-T999
**Android OS**          4.3
**Android Kernel**          3.0.31-1962493
**Android Build**          JSS15J.T999UVUENC2

I think it may be caused by one or more of the following:
- Exiting the app via the Back button (on the device itself) and then going back to the app
- Manually refreshing the Habits by pulling down from the top of the screen.
- **Leaving the Habits list open through a Cron (e.g. midnight) and then doing one of the actions explained above.** <-- I think this is probably the cause, some kind of glitch in refreshing the list data with the new day's database entries.

![dupelist](https://cloud.githubusercontent.com/assets/11235930/7215120/e1dc61ec-e57c-11e4-8ab5-0e0abd734780.png)

**Comment by Sduibek** [comment]
I have the screenshots now.

I think it may be caused by one or both of the following:
- Exiting the app via the Back button (on the device itself) and then going back to the app
- Manually refreshing the Habits by pulling down from the top of the screen.

**Comment by Sduibek** [comment]
![actually-see](https://cloud.githubusercontent.com/assets/11235930/7215092/dd4badaa-e57b-11e4-908f-18a3e112695a.png)
![should-see](https://cloud.githubusercontent.com/assets/11235930/7215093/dd4e69f0-e57b-11e4-9e82-6d2ed9454b18.png)

**Comment by Sduibek** [comment]
**SHOULD SEE:**

![should-see](https://cloud.githubusercontent.com/assets/11235930/7215098/18456072-e57c-11e4-9e4e-182274c73e74.png)

**ACTUALLY SEE:**

![actually-see](https://cloud.githubusercontent.com/assets/11235930/7215099/2081e828-e57c-11e4-9b05-77fb308e039b.png)

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
