### ISSUE TITLE
App force closes on Android 5.0

### ISSUE THREAD

**Issue by tntexplosivesltd** [HabitRPG/habitrpg-mobile#377]
The new update to the app just does not work. Whenever I try to open it the app just force closes. It displays the "HabitRPG" splash screen then just force closes. Every time.
This is really frustrating because I have missed heaps of dailies (it doesn't remind me any more, because it keeps force closing).

Running Android 5.1.1 on a Nexus 5.

**Comment by sgabler** [comment]
I have exactly the same issue on a Motorola Moto G (first gen) with Android 5.0.2

**Comment by bouncyballboy** [comment]
Oddly, I am experiencing the exact same problem running Android 4.2 on Samsung Galaxy Light (SGH-T399). My mobile is rooted, but I didn't have this issue initially (after rooting it). I can't think of any customisations to my device that should affect the app running, although I've tried undoing changes I've made to see if I could find the source of the problem. No luck, however :( . I wonder if the same thing as whatever I did to my OS to smeg it up might be related to the problem on the Android 5 OS?

**Comment by negue** [comment]
I'm really sorry that the app is crashing :/

Could you all un- & reinstall the app? One component which we use to create scheduled notifications switched its ID Value from string to integer (number), even though we cancel all notifications on the app start, it tries to parse a string to a number and then crashes, there is nothing we can do - codewise.

Only an uninstall can delete the saved IDs and then everything should work again. :)

**Comment by sgabler** [comment]
@negue - thanks, that worked for me

**Comment by bouncyballboy** [comment]
The reinstalling didn't work for me, but clearing the data and cache stored
on my device before reinstalling did work :)

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
