### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [HabitRPG/habitrpg-mobile#384]
Please add this to F-Droid.

A thread for it has been created at: https://f-droid.org/forums/topic/habitrpg/

Instructions are at: https://f-droid.org/contribute/

**Comment by crookedneighbor** [comment]
Development on this repo has halted. 

We're actively working on a native Android app and will not be supporting this app much longer.

**Comment by pizzamaker** [comment]
Where can I follow updates?

**Comment by crookedneighbor** [comment]
@pizzamaker I've added a ticket that you can subscribe to here: https://github.com/HabitRPG/habitrpg-mobile/issues/385

Alternatively, you can join the [developers guild](https://habitica.com/#/options/groups/guilds/e655bb46-96ec-4d8b-b40d-f195063904c8) as I plan to announce the release of the android app there as well.
