### ISSUE TITLE
New Android App Watch List [$10]

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitrpg-mobile#385]
This issue serves as a way for users to subscribe to get information about the new Android app when it becomes available. When it is released, the url to the new app will be posted here and this issue will be closed. 

To subscribe to this issue, press the subscribe button.

**Comment by Shadow53** [comment]
All I ask is that the app is provided also as a standalone apk for people to use until F-Droid can get it in their repos.

**Comment by pizzamaker** [comment]
+1

**Comment by willsheppard** [comment]
Thank you. Keep up the great service

**Comment by Atomk** [comment]
Any info on the development?

**Comment by binamkayastha** [comment]
Sorry, I couldn't find a repo for this? I know some native Android App development, and I'd like to contribute.

**Comment by crookedneighbor** [comment]
@binamkayastha When version 1 is released, we'll add the repo here.

**Comment by crookedneighbor** [comment]
By "here", I mean, to this Github organization.

I'll also post a link here to the new repo.

**Comment by Alys** [comment]
We now have a mailing list that you can sign up to for a notification when the new Android app is released: https://habitica.com/static/apps

**Comment by crookedneighbor** [comment]
Closing this in favor of the mailing list option.

**Comment by willsheppard** [comment]
FYI: HabitRPG appears to have been renamed to Habitica.

**Comment by Alys** [comment]
@willsheppard Yes, that's correct. Habitica is the name of the website, and also of the official iOS app. The current official (but old) Android app is still called HabitRPG. The new Android app that will replace it (the one that the mailing list described above is for) will be called Habitica.

**Comment by crookedneighbor** [comment]
The beta for the Android app is out! https://play.google.com/store/apps/details?id=com.habitrpg.android.habitica

**Comment by djibux** [comment]
Yeah!  Congrats.  I can't wait to see it in f-droid.

**Comment by metasean** [comment]
@crookedneighbor - Any ETA on a standalone apk for people to use until F-Droid adds it to their repo?

**Comment by crookedneighbor** [comment]
The repo is here: https://github.com/habitrpg/habitrpg-android
