### ISSUE TITLE
Local npm install failure

### ISSUE THREAD

**Issue by Jazzis18** [HabitRPG/habitrpg-mobile#386]
Hello, I tried to install the habitrpg-mobile on my computer (Ubuntu 14.04) and for `npm install` step in instruction I get the error:
> npm http GET https://registry.npmjs.org/habitrpg
npm http 404 https://registry.npmjs.org/habitrpg
npm ERR! TypeError: Cannot call method 'match' of undefined
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:119:29)
npm ERR!     at cb (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:158:9)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:252:14)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

> npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"

I couldn't install other dependencies, so I removed the `"habitrpg": "HabitRPG/habitrpg#develop"` from package.json. And put it back when set other dependencies. The error remained.

**Comment by huaruiwu** [comment]
installing without #develop seems to install the master branch which is out of date, that's why i put #develop. I did not get that error though.

**Comment by Jazzis18** [comment]
@huaruiwu I removed #develop, but I get the same error :(

**Comment by crookedneighbor** [comment]
@Jazzis18 FYI, this repo will be deprecated soon in favor of native apps and we are no longer accepting pull requests for this repo. 

Were you hoping to contribute to this? Or were you cloning it down for another reason?

**Comment by Jazzis18** [comment]
@crookedneighbor In part, I wanted to see whether it is possible to translate a mobile application. In part, it was just interesting.

**Comment by crookedneighbor** [comment]
@Jazzis18 Soon we're going to be translating the strings for the iOS app. Here's the Transifex project for it: https://www.transifex.com/habitrpg/habitica-ios/dashboard/ (note, nothing has been added to it yet, it's just a placeholder at the moment)

We'll also be translating the new, as of yet, unreleased Android app, but it's not quite ready yet.
