### ISSUE TITLE
Missing equipment 

### ISSUE THREAD

**Issue by rogers85748** [HabitRPG/habitrpg-mobile#391]
The equipment that I have purchased over the last moth or so doesn't appear in the app but it does on the website. This us the case whether I got it on the website or on the app. Thanks for looking into this.  Eric

**Comment by crookedneighbor** [comment]
There's a new version of the app out with the new equipment and pets.

Note: this app is being deprecated in favor of a fully native app (which will not require updates to get the newest equipment/pets). You can subscribe here to be notified when the app will be released: https://habitica.com/static/apps
