### ISSUE TITLE
Completed Dailies didn't register

### ISSUE THREAD

**Issue by Aenith** [HabitRPG/habitrpg-mobile#392]
Hi - I completed all but one of my dailies last night before cron using the android app. Today, I logged in this afternoon to find that I had died (and caused thirty damage to my party). The dailies I had checked off yesterday are still checked off today. What happened? (I've stuck myself in the inn for now to keep from hurting my party further.)

**Comment by crookedneighbor** [comment]
Sorry for taking so long to get back to you. This app is no longer actively developed.

Probably what happened is a sync error, where the app appeared to have synced with the server, but it did not.

I recommend installing the new android app https://play.google.com/store/apps/details?id=com.habitrpg.android.habitica&hl=en
