### ISSUE TITLE
Missing equipment

### ISSUE THREAD

**Issue by BrazilianGal** [HabitRPG/habitrpg-mobile#393]
Some of my equipment is missing. Specifically the "special edition" kind

**Comment by crookedneighbor** [comment]
Are you on iOS or Android?

**Comment by BrazilianGal** [comment]
Android, it don't appear in the app but it does in the site

**Comment by rogers85748** [comment]
Posted a similar issue about a month ago.  Gear showing up on the site but not the app. Also android.

**Comment by crookedneighbor** [comment]
There's a new version of the app out with the new equipment and pets.

Note: this app is being deprecated in favor of a fully native app (which will not require updates to get the newest equipment/pets). You can subscribe here to be notified when the app will be released: https://habitica.com/static/apps
