### ISSUE TITLE
Now that I am a mage, the entry level gear does not show up in Rewards

### ISSUE THREAD

**Issue by adam-jensen** [HabitRPG/habitrpg-mobile#394]
Version 1.0.2 (67)
iPhone 6

Repro steps:
Given that it is fall, and I am a level 11 warrior with some assorted warrior gear (red helmet, chainmail shirt, etc)
When I change class (for the first time) to mage at level 11 (after putting off the change initially)
Then,
Actual result: Only the seasonal gear (stitched robes, stitched hat, enchanted thread) and the health potion are available to purchase on the rewards tab of the mobile app
Expected result: the entry-level, 20 gp-ish mage gear should also available for purchase alongside the seasonal items

**Comment by crookedneighbor** [comment]
This repo is for the old habitrpg app (brown chest icon). I've made an issue for you on the habitica repo: https://github.com/HabitRPG/habitrpg-ios/issues/272

**Comment by adam-jensen** [comment]
@crookedneighbor I actually see a purple icon with a white griffin. Am I using the wrong app?

**Comment by adam-jensen** [comment]
I found the app by searching "habitica" in the ios app store. That says the latest version is 1.0.2. I think this issue should be re-opened unless I am completely off base somehow.

**Comment by adam-jensen** [comment]
I see the old brown chest version version in the store, and it is version 0.0.57. I included the version number at the top of my report.

**Comment by crookedneighbor** [comment]
You're using the correct app, but reporting it in the wrong repository :smile: don't worry. I opened a new issue for you in the correct place so the devs that work on the iOS app can see it. This repository is for the older app.
