### ISSUE TITLE
Internet-related toasts outside the app. 

### ISSUE THREAD

**Issue by alextpedro** [HabitRPG/habitrpg-mobile#398]
I've been getting toasts saying things like  "your Internet just got back!" even while not using the app. While these might be (nominally) useful inside the app, they're invasive outside it.

**Comment by crookedneighbor** [comment]
Are you referring to the old app (brown treasure chest logo), the new iOS app (purple gryphon logo) or the new beta Android app (purple gryphon logo)?

This repository is for the old app (and it will be shut down as soon as the new Android app is out of beta).

**Comment by alextpedro** [comment]
Ah my bad. It's for the new Android one but the url included with the app gave me a 404.

**Comment by crookedneighbor** [comment]
This issue should be fixed now, the repo for the new app is  https://github.com/HabitRPG/habitrpg-android

It wasn't a public repo at the time of the initial release.
