### ISSUE TITLE
Android version issues

### ISSUE THREAD

**Issue by Kathryn-the-Writer** [HabitRPG/habitrpg-mobile#399]
Great job, guys! Some things I spotted after today's update (all aesthetic):

1. Images in task names (e.g. :car:) don't show.
2. Dailies tab shows all tasks; no way to show only  Due Dailies.
3. Rewards in a weird order.

**Comment by crookedneighbor** [comment]
@Kathryn-the-Writer Would you mind posting this on the app's repo? https://github.com/HabitRPG/habitrpg-android/issues

This repo is the old, no longer supported app.
