### ISSUE TITLE
Android unable to login using FB

### ISSUE THREAD

**Issue by bas-deweerd** [HabitRPG/habitrpg-mobile#400]
I'm unable to login the app using my facebook. I get the following error: "Given URL is not permitted by the Application configuration: One or more of the given URLs is not permitted by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains."

I have tried to reinstall the app and I get the same error.

HabitRPG v: 0.0.60
Phone: Oneplus One
Android v: 5.1.1
Cyanogen OS v: 12.1-YOG4PAS3JL 

User ID: f067d16f-b88f-47d5-a094-f50a36efffbe

**Comment by legovader09** [comment]
I can confirm this, getting the same error but on Android 4.4.2 using Honor Holly.

**Comment by JosefHruska** [comment]
Same problem.

**Comment by crookedneighbor** [comment]
Are y'all using the old, no longer supported app (brown chest, this repo) or the new android app (purple gryphon, [this other repo](https://github.com/HabitRPG/habitrpg-android))

If you're using the old one, please upgrade to the new app. https://play.google.com/store/apps/details?id=com.habitrpg.android.habitica&hl=en

If you're using the new app, please open an issue on the new app's github repo so our android devs can see it and address it: https://github.com/HabitRPG/habitrpg-android/issues

**Comment by bas-deweerd** [comment]
Awesome thanks, I was indeed using the HabitRPG (brown chest) app.
