### ISSUE TITLE
can't log tasks

### ISSUE THREAD

**Issue by pookarah** [HabitRPG/habitrpg-mobile#401]
I can enter them as things to do, but the app will not let me mark them as done.

Am on LG Enact running Android.

**Comment by paglias** [comment]
@pookarah hi, this app is no longer developed nor maintained.

We've switched to native apps for Android and iOS:

### iOS
- [GitHub](https://github.com/HabitRPG/habitrpg-ios)
- [App Store](https://itunes.apple.com/us/app/habitica/id994882113?ls=1&mt=8)

# Android
- [GitHub](https://github.com/HabitRPG/habitrpg-android)
- [Google Play](https://play.google.com/store/apps/details?id=com.habitrpg.android.habitica)

**Comment by pookarah** [comment]
OK, thanks :)
