### ISSUE TITLE
Equipment Bug

### ISSUE THREAD

**Issue by pjputzel** [HabitRPG/habitrpg-mobile#402]
I just purchased upgrades for all my equipment. The new equipment did not show up in my inventory although the store no lonhlger displays them for sale (the next set is displayed for sale currently). I restarted the app multiple times, checked the website, and used check character values. The equipment doesn't show up anywhere (and I lost gold). The set I attempted to buy was the hat and robe that come after the archmage hat and robe, and the staff that comes after the brobze staff. I can give my id if needed.

**Comment by paglias** [comment]
@pjputzel hi, this app is no longer developed nor maintained.

We've switched to native apps for Android and iOS:

### iOS
- [GitHub](https://github.com/HabitRPG/habitrpg-ios)
- [App Store](https://itunes.apple.com/us/app/habitica/id994882113?ls=1&mt=8)

# Android
- [GitHub](https://github.com/HabitRPG/habitrpg-android)
- [Google Play](https://play.google.com/store/apps/details?id=com.habitrpg.android.habitica)
