### ISSUE TITLE
ToDo list on the Android app "forgets" items strangely ...

### ISSUE THREAD

**Issue by stephenisthebaker** [HabitRPG/habitrpg-mobile#403]
I am using v0.0.60 of the HabitRPG Android app.

My device is a Google Nexus 6P by Huawei, running Android Marshmallow v6.0.1 (build MMB29P).

So I love the app and web version!  I prefer the Android app for the user interface, which is much easier to use on a mobile device (even on my ginormous 5.7" screen).

When I'm using the ToDo list column, sometimes when trying to use the "move" mode to re-order ToDo items, I get a message stating "Task Not Found".  (This also happens when re-ordering tasks in the Habits and Dailies columns, only less frequently).  

When this happens, I generally have to mess around with trying to get the app and website in sync again.

I'll try several things, such as:

* I try the "pull down" to refresh, which never seems to help.

* I try force stopping the app, then restarting, which seldom helps.

* I try deleting the item, then recreating it, then re-ordering the tasks with the "move" mode, which works for the one item, but I usually end up recreating the entire list as each 2nd or 3rd item throws the same "Task Not Found" error.

* I try using the Desktop version on my PC to re-order the tasks.  This works, but then it takes several minutes to get the Android app to sync with these changes.

* I often just close the app and come back to it in an hour or so and everything is working again.

My thought is: there must be a database field for the "Sort Order" which is included in the "Move Mode" class method that is expecting the old order value, so the SQL (or hash table) query returns nothing, thus "Task Not Found".  (I have not taken there time to read the code, so forgive me if I'm either off here or if it would be obvious.  I plan to review the code and I'm considering making contributions in the future, as soon as my schedule allows :-D )

Thanks in advance!  If y'all would like more details let me know.

Also:  thanks for a great and awesome thing!  This was as genious idea!  (Looking into the many GTD implementations next weekend :-D )

-stephenisthebaker@

**Comment by paglias** [comment]
@stephenisthebaker hi! this app is no longer developed nor maintained.

We've switched to native apps for Android and iOS:

### iOS
- [GitHub](https://github.com/HabitRPG/habitrpg-ios)
- [App Store](https://itunes.apple.com/us/app/habitica/id994882113?ls=1&mt=8)

# Android
- [GitHub](https://github.com/HabitRPG/habitrpg-android)
- [Google Play](https://play.google.com/store/apps/details?id=com.habitrpg.android.habitica)
