### ISSUE TITLE
'Error contacting the server' message on start-up of app

### ISSUE THREAD

**Issue by tintinkerer** [HabitRPG/habitrpg-mobile#406]
Regardless of the status of my internet connection, every time I open the app on my phone, I get a yellow ribbon at the top telling me that there is a problem contacting the server.

However, there doesn't actually appear to be a problem with the server; I'm able to do everything I should.

**Comment by phillipthelen** [comment]
Are you having this issue with the old HabitRPG app or one of the new Habitica native apps?
This is the repository for the old app. This app is no longer supported and will not receive any further updates.

If you are having the issue with one of the new apps, feel free to open an issue for those in the [android](https://github.com/HabitRPG/habitrpg-android/issues) or [iOS](https://github.com/HabitRPG/habitrpg-ios/issues) repositoy.
